# -*- coding: utf-8 -*-
"""codejamQ2019.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E6gQJX4Xoj-_Toldhj9p7sMBkCaCCm21

#  Codejam Qualification Round 2019

# Task 1 Foregone Solution

$\displaystyle{\mathbb{\color{steelblue}{Problem}}}$

Someone just won the Code Jam lottery, and we owe them N jamcoins! 

However, when we tried to print out an oversized check, we encountered a problem. 

The value of N, which is an integer, includes at least one digit that is a 4... 

and the 4 key on the keyboard of our oversized check printer is broken.

Fortunately, we have a workaround: 

we will send our winner two checks for positive integer amounts A and B, 

such that neither A nor B contains any digit that is a 4, and A + B = N. 

Please help us find any pair of values A and B that satisfy these conditions.

$Input$

The first line of the input gives the number of test cases, T. 

T test cases follow; each consists of one line with an integer N.

$Output$

For each test case, output one line containing `Case #x: A B`, 

where x is the test case number (starting from 1), and 

A and B are positive integers as described above.

It is guaranteed that at least one solution exists. 

If there are multiple solutions, you may output any one of them. 

(See "What if a test case has multiple correct solutions?" in the Competing section of the FAQ. 

This information about multiple solutions will not be explicitly stated in the remainder of the 2019 contest.)

$Limits$

1 ≤ T ≤ 100.

Time limit: 10 seconds per test set.

Memory limit: 1GB.

At least one of the digits of N is a 4.

Test set 1 (Visible)

1 < N < 105.

Test set 2 (Visible)

1 < N < 109.

Solving the first two test sets for this problem should get you a long way toward advancing. 

The third test set is worth only 1 extra point, for extra fun and bragging rights!

Test set 3 (Hidden)

1 < N < 10100.
"""

'''
Sample

Input  
 
3

4
940
4444

Output
  
Case #1: 2 2
Case #2: 852 88
Case #3: 667 3777
'''

T = int(input())
try:
    for i in range(T):
        S = input()
        A = ''
        for j in range(1,len(S)+1):
            if int(S[-j]) == 4:
                A = '1' + A
            else:
                A = S[-j] + A
        B = str(int(S) - int(A))
        print('Case #{}: '.format(i+1), A, B)
except StopIteration: pass

"""# Task 2 You Can Go Your Own Way

$\displaystyle{\mathbb{\color{steelblue}{Problem}}}$

You have just entered the world's easiest maze. 

You start in the northwest cell of an N by N grid of unit cells, and you must reach the southeast cell. 

You have only two types of moves available: a unit move to the east, and a unit move to the south. 

You can move into any cell, but you may not make a move that would cause you to leave the grid.

You are excited to be the first in the world to solve the maze, but then you see footprints. 

Your rival, Labyrinth Lydia, has already solved the maze before you, using the same rules described above!

As an original thinker, you do not want to reuse any of Lydia's moves. 

Specifically, if her path includes a unit move from some cell A to some adjacent cell B, 

your path cannot also include a move from A to B.

(However, in that case, it is OK for your path to visit A or visit B, as long as you do not go from A to B.) 

Please find such a path.

In the following picture, Lydia's path is indicated in blue, 

and one possible valid path for you is indicated in orange:

$Input$

The first line of the input gives the number of test cases, T. 

T test cases follow; each case consists of two lines. 

The first line contains one integer N, giving the dimensions of the maze, as described above. 

The second line contains a string P of 2N - 2 characters,

each of which is either uppercase E (for east) or uppercase S (for south), 

representing Lydia's valid path through the maze.

$Output$

For each test case, output one line containing `Case #x: y`, 

where x is the test case number (starting from 1) and 

y is a string of 2N - 2 characters each of which is either uppercase E (for east) or uppercase S (for south),

representing your valid path through the maze that does not conflict with Lydia's path, as described above. 

It is guaranteed that at least one answer exists.

$Limits$

1 ≤ T ≤ 100.

Time limit: 15 seconds per test set.

Memory limit: 1GB.

P contains exactly N - 1 E characters and exactly N - 1 S characters.

Test set 1 (Visible)

2 ≤ N ≤ 10.

Test set 2 (Visible)

2 ≤ N ≤ 1000.

Test set 3 (Hidden)

For at most 10 cases, 2 ≤ N ≤ 50000.

For all other cases, 2 ≤ N ≤ 10000.


In `Sample Case #1`, the maze is so small that there is only one valid solution left for us.

`Sample Case #2 `corresponds to the picture above. 

Notice that it is acceptable for the paths to cross.

Sample

Input 
 
2
2
SE
5
EESSSESE

Output

Case #1: ES
Case #2: SEEESSES
"""

T = int(input())
try:
    for i in range(T):
        L = int(input())
        S = input()
        W = S.replace('S','L').replace('E','S').replace('L','E')
        print('Case #{}: '.format(i+1), W)
except StopIteration: pass

"""# Task 3 Cryptopangrams (10pts, 15pts)

$\displaystyle{\mathbb{\color{steelblue}{Problem}}}$

On the Code Jam team, we enjoy sending each other pangrams, 

which are phrases that use each letter of the English alphabet at least once. 

One common example of a pangram is "the quick brown fox jumps over the lazy dog". 

Sometimes our pangrams contain confidential information — for example, CJ QUIZ: 

KNOW BEVY OF DP FLUX ALGORITHMS — so we need to keep them secure.

We looked through a cryptography textbook for a few minutes, 

and we learned that it is very hard to factor products of two large prime numbers, 

so we devised an encryption scheme based on that fact. 

First, we made some preparations:

We chose 26 different prime numbers, none of which is larger than some integer N.

We sorted those primes in increasing order. 

Then, we assigned the smallest prime to the letter A, 

the second smallest prime to the letter B, and so on.

Everyone on the team memorized this list.

Now, whenever we want to send a pangram as a message, 

we first remove all spacing to form a plaintext message. 

Then we write down the product of the prime for the first letter of the plaintext and 

the prime for the second letter of the plaintext. 

Then we write down the product of the primes for the second and third plaintext letters, and so on, 

ending with the product of the primes for the next-to-last and last plaintext letters. 

This new list of values is our ciphertext. 

The number of values is one smaller than the number of characters in the plaintext message.

For example, suppose that N = 103 and we chose to use the first 26 odd prime numbers, 

because we worry that it is too easy to factor even numbers. 

Then A = 3, B = 5, C = 7, D = 11, and so on, up to Z = 103. 

Also suppose that we want to encrypt the CJ QUIZ... pangram above, 

so our plaintext is `CJQUIZKNOWBEVYOFDPFLUXALGORITHMS`. 

Then the first value in our ciphertext is 7 (the prime for C) times 31 (the prime for J) = 217; 

the next value is 1891, and so on, ending with 3053.

We will give you a ciphertext message and the value of N that we used. 

We will not tell you which primes we used, or how to decrypt the ciphertext. 

Do you think you can recover the plaintext anyway?

$Input$

The first line of the input gives the number of test cases, T. 

T test cases follow; each test case consists of two lines. 

The first line contains two integers: 

N, as described above, and L, the length of the list of values in the ciphertext. 

The second line contains L integers: the list of values in the ciphertext.

$Output$

For each test case, output one line containing 

`Case #x: y`, 

where x is the test case number (starting from 1) and y is a string of L + 1 

uppercase English alphabet letters: the plaintext.

$Limits$

1 ≤ T ≤ 100.

Time limit: 20 seconds per test set.

Memory limit: 1 GB.

25 ≤ L ≤ 100.

The plaintext contains each English alphabet letter at least once.

Test set 1 (Visible)

101 ≤ N ≤ 10000.

Test set 2 (Hidden)

101 ≤ N ≤ 10100.

$Sample$

$Input$ 
 	
2

103 31

217 1891 4819 2291 2987 3811 1739 2491 4717 445 65 1079 8383 5353 901 187 649 1003 697 3239 7663 291 123 779 1007 3551 1943 2117 1679 989 3053

10000 25

3292937 175597 18779 50429 375469 1651121 2102 3722 2376497 611683 489059 2328901 3150061 829981 421301 76409 38477 291931 730241 959821 1664197 3057407 4267589 4729181 5335543

$Output$
 
Case #1: CJQUIZKNOWBEVYOFDPFLUXALGORITHMS

Case #2: SUBDERMATOGLYPHICFJKNQVWXZ

"""

T = int(input())
Letters = list('ABCDEFGHIJKLMNOPQRSTUVWXYZ')
for i in range(T):
    S1 = input().split()
    P,N = int(S1[0]),int(S1[1])
    S2 = input().split()
    for p in range(2, int(int(S2[0])**0.5)+1):
        if int(S2[0]) % p == 0:
            primes = [p]
            primes_unique = primes
            break
    p = int(int(S2[0]) / primes[0])
    if int(S2[1]) % primes[0] == 0:
        primes = [p] + primes
    else:
        primes = primes + [p]
    if p not in primes_unique:
        primes_unique.append(p) 
        
    for j in range(1,N):
        p = int(int(S2[j]) / primes[j])
        primes.append(p) 
        if p not in primes_unique:
            primes_unique.append(p)
    D = dict(zip(sorted(primes_unique),Letters))
    S=''
    for el in primes:
        S += D[el]
    print('Case #{}:'.format(i+1), S)

import numpy as np
Letters = list('ABCDEFGHIJKLMNOPQRSTUVWXYZ')
T = int(input())
try:
    for k in range(T):
        S1 = input().split()
        P,N = int(S1[0]),int(S1[1])
        S2 = input().split()
        s = np.ones(int((P+1)/2), dtype=np.bool)
        for i in range(3,int((P+1)**0.5)+1,2):
            if s[int(i/2)]:
                s[int(i*i/2)::i] = False
        Primes = np.r_[2, 2*np.nonzero(s)[0][1::]+1] 
        for p in Primes:
            if int(S2[0]) % p == 0:
                primes = [p]
                break
        p = int(int(S2[0]) / primes[0])
        if int(S2[1]) % primes[0] == 0:
            primes = [p] + primes
        else:
            primes = primes + [p]
            
        for j in range(1,N):
            p = int(int(S2[j]) / primes[j])
            primes.append(p) 
            
        primes_unique, indices = np.unique(primes, return_inverse=True)
        S=''
        for ind in indices:
            S += Letters[ind]
        print('Case #{}:'.format(k+1), S)            
except StopIteration: pass

"""2

103 31

217 1891 4819 2291 2987 3811 1739 2491 4717 445 65 1079 8383 5353 901 187 649 1003 697 3239 7663 291 123 779 1007 3551 1943 2117 1679 989 3053

10000 25

3292937 175597 18779 50429 375469 1651121 2102 3722 2376497 611683 489059 2328901 3150061 829981 421301 76409 38477 291931 730241 959821 1664197 3057407 4267589 4729181 5335543
"""

import numpy as np
N = 103
s = np.ones(int((N+1)/2), dtype=np.bool)
for i in range(3,int((N+1)**0.5)+1,2):
    if s[int(i/2)]:
        s[int(i*i/2)::i] = False
Primes = np.r_[2, 2*np.nonzero(s)[0][1::]+1]  
Primes

def isprime(num):
    if num in [0,1]:
        return False
    for x in range(2,num):
        if num%x==0:
            return False
    else:
        return True
for i in range(20):
    print(i,isprime(i))

def isprime(num):
    if num in [0,1]:
        return False
    for x in range(2,num):
        if num%x==0:
            return False
    else:
        return True
def prime_list0(max_num,count):
    pl=[max_num]
    c,curr_num=1,max_num
    while c<count:
        curr_num-=2
        if isprime(curr_num):
            pl=[curr_num]+pl
            c+=1
    return pl
max_num,count=103,26
pl=prime_list0(max_num,count)
print(pl)

num_list=[217,1891,4819,2291,2987,3811,1739,
          2491,4717,445,65,1079,8383,5353,901,
          187,649,1003,697,3239,7663,291,123,
          779,1007,3551,1943,2117,1679,989,3053]
num_len=31
def crypto0(max_num=max_num,num_len=num_len,num_list=num_list):
    pl=prime_list(max_num,count=26)
    ll=list('ABCDEFGHIJKLMNOPQRSTUVWXYZ')
    dl=dict(zip(pl,ll))
    for p in pl:
        if num_list[0]%p==0:
            break
    crypto_list=dl[p]
    for i in range(num_len):
        crypto_list+=dl[num_list[i]//p]
        p=num_list[i]//p
    return crypto_list

crypto()

num_list=[3292937,175597,18779,50429,375469,1651121,2102,
          3722,2376497,611683,489059,2328901,3150061,
          829981,421301,76409,38477,291931,730241,959821,
          1664197,3057407,4267589,4729181,5335543]
max_num,num_len=10000,25
def prime_list(max_num=max_num):
    while not isprime(max_num):
        max_num-=1
    pl=[max_num]
    while max_num>2:
        max_num-=2
        if isprime(max_num):
            pl=[max_num]+pl
    return pl
def crypto(max_num=max_num,num_len=num_len,num_list=num_list):
    pl=prime_list(max_num)
    for p in pl:
        if num_list[0]%p==0:
            break
    crypto_list,prime_set=[p],[p]
    for i in range(num_len):
        crypto_list+=[num_list[i]//p]
        p=num_list[i]//p
        if p not in prime_set:
            prime_set+=[p]
    prime_set=sorted(prime_set)
    letter_set=list('ABCDEFGHIJKLMNOPQRSTUVWXYZ')
    dl=dict(zip(prime_set,letter_set))
    crypto_str=''
    for i in range(num_len):
        crypto_str+=dl[crypto_list[i]]
    return crypto_str
crypto()

def isprime(num):
    if num in [0,1]:
        return False
    for x in range(2,num):
        if num%x==0:
            return False
    else:
        return True
def prime_list(max_num):
    while not isprime(max_num):
        max_num-=1
    pl=[max_num]
    while max_num>2:
        max_num-=2
        if isprime(max_num):
            pl=[max_num]+pl
    return pl
def crypto(max_num,num_len,num_list):
    pl=prime_list(max_num)
    for p in pl:
        if num_list[0]%p==0:
            break
    crypto_list,prime_set=[p],[p]
    for i in range(num_len):
        crypto_list+=[num_list[i]//p]
        p=num_list[i]//p
        if p not in prime_set:
            prime_set+=[p]
    prime_set=sorted(prime_set)
    letter_set=list('ABCDEFGHIJKLMNOPQRSTUVWXYZ')
    dl=dict(zip(prime_set,letter_set))
    crypto_str=''
    for i in range(num_len+1):
        crypto_str+=dl[crypto_list[i]]
    return crypto_str
T=int(input())
for t in range(T):
    max_num,num_len=map(int,input().split())
    num_list=list(map(int,input().split()))
    ans=crypto(max_num,num_len,num_list)
    print('Case #{}: {}'.format(t+1,ans))

def replace_zero(num_list,num_len,crypto_list):
    for i in range(num_len):
        if (crypto_list[i]==0) and (crypto_list[i+1]!=0):
            crypto_list[i]=num_list[i]//crypto_list[i+1]
        if (crypto_list[i]!=0) and (crypto_list[i+1]==0):
            crypto_list[i+1]=num_list[i+1]//crypto_list[i]
    return crypto_list

num_list=[3292937,175597,18779,50429,375469,1651121,2102,
          3722,2376497,611683,489059,2328901,3150061,
          829981,421301,76409,38477,291931,730241,959821,
          1664197,3057407,4267589,4729181,5335543]
max_num,num_len=10000,25
def eacd(a,b):
    if b==0:
        return a
    else:
        return eacd(b,a%b)
def replace_zero(num_list,num_len,crypto_list):
    for i in range(num_len):
        if (crypto_list[i]==0) and (crypto_list[i+1]!=0):
            crypto_list[i]=num_list[i]//crypto_list[i+1]
        if (crypto_list[i]!=0) and (crypto_list[i+1]==0):
            crypto_list[i+1]=num_list[i]//crypto_list[i]
    return crypto_list
def crypto_string(num_list,num_len):
    crypto_list=(num_len+1)*[0]
    for i in range(num_len-1):
        if num_list[i]!=num_list[i+1]:
            crypto_list[i+1]=eacd(num_list[i],num_list[i+1])
    while 0 in crypto_list:
        crypto_list=replace_zero(num_list,num_len,crypto_list)
    prime_set=list(set(crypto_list))
    prime_set.sort()
    letter_set=list('ABCDEFGHIJKLMNOPQRSTUVWXYZ')
    dl=dict(zip(prime_set,letter_set))
    crypto_str=''
    for i in range(num_len+1):
        crypto_str+=dl[crypto_list[i]]
    return crypto_str
crypto_string(num_list,num_len)

def eacd(a,b):
    if b==0:
        return a
    else:
        return eacd(b,a%b)
def crypto_string(num_list,num_len):
    p1=eacd(num_list[0],num_list[1])
    p0=num_list[0]//p1
    crypto_list=[p0,p1]
    for i in range(1,num_len):
        p1=num_list[i]//p1
        crypto_list.append(p1)
    prime_set=list(set(crypto_list))
    prime_set.sort()
    letter_set=list('ABCDEFGHIJKLMNOPQRSTUVWXYZ')
    dl=dict(zip(prime_set,letter_set))
    crypto_str=''
    for i in range(num_len+1):
        crypto_str+=dl[crypto_list[i]]
    return crypto_str
T=int(input())
for t in range(T):
    max_num,num_len=map(int,input().split())
    num_list=list(map(int,input().split()))
    answer=crypto_string(num_list,num_len)
    print('Case #{}: {}'.format(t+1,answer))

"""# Task 4

$\displaystyle{\mathbb{\color{steelblue}{Problem}}}$

A research consortium has built a new database system for their new data center. 

The database is made up of one master computer and N worker computers, which are given IDs from 0 to N-1. 

Each worker stores exactly one bit of information... 

which seems rather wasteful, but this is very important data!

You have been hired to evaluate the following instruction for the database:

TEST_STORE <bits>: 

The master reads in <bits>, which is a string of N bits, and sends the i-th bit to the i-th worker for storage.

The master will then read the bits back from the workers and return them to the user, 

in the same order in which they were read in.

During normal operation, TEST_STORE should return the same string of bits that it read in, 

but unfortunately, B of the workers are broken!

The broken workers are correctly able to store the bits given to them, 

but whenever the master tries to read from a broken worker, no bit is returned. 

This causes the TEST_STORE operation to return only N-B bits, 

which are the bits stored on the non-broken workers (in ascending order of their IDs). 

For example, suppose N = 5 and the 0th and 3rd workers are broken (so B = 2). Then:

`TEST_STORE 01101 returns 111`.

`TEST_STORE 00110 returns 010`.

`TEST_STORE 01010 returns 100`.

`TEST_STORE 11010 also returns 100`.

For security reasons, the database is hidden in an underground mountain vault, 

so calls to TEST_STORE take a very long time. 

You have been tasked with working out which workers are broken using at most F calls to TEST_STORE.

$Input \; and \; output$

This is an interactive problem. 

You should make sure you have read the information in the Interactive Problems section of our FAQ.

Initially, your program should read a single line containing a single integer T indicating the number of test cases. 

Then, you need to process T test cases.

For each test case, your program will first read a single line 

containing three integers N, B, and F,

- indicating the number of workers, 
- the number of broken workers, 
- and the number of lines you may send 

(as described below).

Then you may send the judge up to F lines, each containing a string of exactly N characters, each either 0 or 1. 

Each time you send a line, the judge will check that you have not made more than F calls. 

If you have, the judge will send you a single line containing a single -1, and then finish all communication and wait for your program to finish. 

Otherwise, the judge will send a string of length N-B: the string returned by TEST_STORE, as described above.

Once your program knows the index of the B broken workers, 

it can finish the test case by sending B space-separated integers: 

the IDs of the broken workers, in sorted order. 

This does not count as one of your F calls.

If the B integers are not exactly the IDs of the B broken workers, 

you will receive a Wrong Answer verdict, and the judge will send a single line containing -1, 

and then no additional communication. 

If your answer was correct, the judge will send a single line with 1, 

followed by the line that begins the next test case (or exit, if that was the last test case).

$Limits$

Time limit: 20 seconds per test set.

Memory limit: 1GB.

1 ≤ T ≤ 100.

2 ≤ N ≤ 1024.

1 ≤ B ≤ min(15, N-1).

Test set 1 (Visible)

F = 10.

Test set 2 (Hidden)

F = 5.

Testing Tool

You can use this testing tool to test locally or on our servers. 

To test locally, you will need to run the tool in parallel with your code; 

you can use our interactive runner for that. 

For more information, read the Interactive Problems section of the FAQ.

Local Testing Tool

To better facilitate local testing, we provide you the following script. 

Instructions are included inside. 

You are encouraged to add more test cases for better testing. 

Please be advised that although the testing tool is intended 

to simulate the judging system, 

it is NOT the real judging system and might behave differently.

If your code passes the testing tool but fails the real judge, 

please check here to make sure that you are using the same compiler as us.
"""

Sample Interaction

The following interaction meets the limits for Test set 1.

  t = readline_int()           // Reads 2 into t
  n, b, f = readline_int_list()  // Reads 5, 2, 10 into n, b, f
  printline 01101 to stdout    // The next four outputs match the example in
                               // the problem statement.
  flush stdout
  response = readline_str()    // Reads 111 into response. (At this point, we
                               // could determine the answer; the remaining
                               // queries are just examples!)
  printline 00110 to stdout
  flush stdout
  response = readline_str()    // Reads 010 into response
  printline 01010 to stdout
  flush stdout
  response = readline_str()    // Reads 100 into response
  printline 11010 to stdout
  flush stdout
  response = readline_str()    // Reads 100 into response
  printline 0 3 to stdout      // Guesses the answer. Notice that we were
                               // not required to use all 10 of our allowed
                               // queries.
  flush stdout
  verdict = readline_int()     // Reads 1 into verdict. We got that test case
                               // right!
  n, b, f = readline_int_list()  // Reads 2, 1, 10 into n, b, f.
  printline 01 to stdout       // 01 is a query, not a guess at the final
                               // answer (if we wanted to guess that just
                               // worker 1 were broken, we would have to
                               // send 1 as we do below)
  flush stdout
  response = readline_str()    // Reads 1 into response.
  printline 1 to stdout        // Makes a (bad) wild guess.
  verdict = readline_str()     // Reads -1 into verdict.
  exit                         // exits to avoid an ambiguous TLE error

T = int(input())
try:
    for i in range(T):
        S = input().split()
        S = [int(s) for s in S]
        N, B, F = S[0], S[1], S[2]
        broken = [int(N/B) * i for i in range(B)]
        correct = ' '.join([str(i+1) for i in range(N) if i not in broken])
        j = 0
        while j < F + 1:
            if j == F:
                print(-1, flush=True)
                break
            else:
                string = input()
                if len(string.split()) > 1:
                    if string == correct:
                        print(1, flush=True)
                        break
                    else:
                        print(-1, flush=True)
                        break                        
                else:    
                    answer = ''.join([string[i] for i in range(N) if i not in broken])
                    print(answer, flush=True)
                    j += 1
except StopIteration: pass

T =int(input())
try:
    for i in range(T):
        S = input().split()
        S = [int(s) for s in S]
        N, B, F = S[0], S[1], S[2]
except StopIteration: pass

"""## Column Decoding"""

def output_rows(N):
    outr=[]
    n=len(bin(N-1)[2:])
    for i in range(N):
        bi=bin(i)[2:]
        bit=(n-len(bi))*'0'+bi
        outr.append(bit)
    return outr
outr=output_rows(16)
for r in outr:
    print(r,'-',int(r,2))

N,B=1024,15
(N-1).bit_length(),B.bit_length()

M,F=1024,5; i=5
Mb=(M-1).bit_length()
for i in range(16,32):
    print(format(i,'#0%db'%(Mb+2))[-F:])

N,B=32,15
for j in range(B.bit_length()):
    print([((i%(2**B.bit_length()))>>j)&1 for i in range(N)])

N=1024
Nb=(N-1).bit_length()
outcols=[format(i,'#0%db'%(Nb+2))[2:] for i in range(N)]
incols=N*['']
outrows=[]
for j in range(5):
    outrow=''.join([outcols[i][Nb-j-1] for i in range(N)])
    print(outrow[:100])
    outrows.append(outrow[:77])

exp_result=[2,7,8,12,33,45,46,52,61,71,72,73,74,75,76]
N,B,F=77,len(exp_result),5
inrows=[''.join([outrows[i][j] for j in range(N) 
                 if j not in exp_result])
        for i in range(F)]
inrows

F,N,B=5,77,15
def dat_bae(N,B,F):
    Nb=(N-1).bit_length()
    outcols=[format(i,'#0%db'%(Nb+2))[-F:]
             for i in range(N)]
    incols=N*['']
    for j in range(F):
        outrow=''.join(
            [outcols[i][F-1-j] for i in range(N)])
        print(outrow,flush=True)
        inrow=input()
        for i in range(N-B):
            incols[i]=inrow[i]+incols[i]
    return outcols,incols
outcols,incols=dat_bae(N,B,F)
print(outcols[:12]); print(incols[:12])

N,B,K=77,15,32
Kb=(K-1).bit_length() #Kb==F
exp_result=[2,7,8,12,33,45,46,52,61,71,72,73,74,75,76]
outcol=[format(i,'#0%db'%(Kb+2))[2:] for i in range(K)]
outcols=[outcol[j%K] for j in range(N)]
print(outcols[61:])
inrows=\
['01101010110101010101010101010010101010101010110101010010101010',
 '00100101101100110011001100110110011001101001101100110110011001',
 '00011100011100001111000011110001111000011000011100001110000111',
 '00000011111100000000111111110000000111111000000011111110000000',
 '00000000000011111111111111110000000000000111111111111110000000']
incols=N*['']
for j in range(Kb):
    for i in range(N-B):
        incols[i]=inrows[j][i]+incols[i]
print(incols[61:])

def dat_bae32(N,B):
    K=32; Kb=K.bit_length()-1
    outcol=[format(i,'#0%db'%(Kb+2))[2:] for i in range(K)]
    outcols=[outcol[j%K] for j in range(N)]
    incols=(N-B)*['']
    for j in range(Kb):
        row=[outcol[i][Kb-j-1] for i in range(K)]
        outrow=[row[j%K] for j in range(N)]
        outstr=''.join(outrow)
        print(outstr,flush=True)
        inrow=input()
        for i in range(N-B):
            incols[i]=inrow[i]+incols[i]
    return incols,outcols
incols,outcols=dat_bae32(N,B)
print(outcols[58:])
print(incols[58:])

def dat_bae_answer(N,B,incols,outcols):
    answer,boolean_answer,L=[],False,16
    K,la=(N-B)//L+1,len(answer)
    for k in range(K+1):
        curr_incols=incols[L*k-la:L*(k+1)-la]
        curr_outcols=outcols[L*k:L*(k+1)]
        for i in range(len(curr_outcols)):
            if curr_outcols[i] not in curr_incols:
                answer.append(L*k+i)
                la=len(answer)
                if la==B:
                    booleban_answer=True
                    break
        if boolean_answer:
            break
    return answer
answer=dat_bae_answer(N,B,incols,outcols)
answer==exp_result

"""## Decision Variants"""

def dat_bae(N,B,F):
    Nb=(N-1).bit_length()
    outcols=[format(i,'#0%db'%(Nb+2))[2:]
             for i in range(N)]
    incols=N*['']
    for j in range(Nb):
        if j>F-1:
            break
        outrow=''.join(
            [outcols[i][Nb-j-1] for i in range(N)])
        print(outrow,flush=True)
        inrow=input()
        for i in range(N-B):
            incols[i]=inrow[i]+incols[i]
    answer=[]
    for i in range(N):
        if len(answer)>B:
            break
        if outcols[i] not in incols:
            answer.append(i)
    print(' '.join(map(str,answer)),flush=True)
    ans=input()
    if ans!='1':  
        exit()              
T=int(input())
for i in range(T):
    N,B,F=map(int,input().split())
    dat_bae(N,B,F)

def dat_bae_cols(N,B,F):
    Nb=(N-1).bit_length()
    outcols=[format(i,'#0%db'%(Nb+2))[2:]
             for i in range(N)]
    incols=N*['']
    for j in range(Nb):
        if j>F-1:
            break
        outrow=''.join(
            [outcols[i][Nb-j-1] for i in range(N)])
        print(outrow,flush=True)
        inrow=input()
        for i in range(N-B):
            incols[i]=inrow[i]+incols[i]
    return outcols,incols
def dat_bae_ans(N,B,F,outcols,incols):    
    answer=[]
    for i in range(N):
        if outcols[i] not in incols:
            answer.append(i)
            if len(answer)==B:
                break
    return answer
def dat_bae_fans(N,B,F,outcols,incols):    
    answer,boolean_answer,L=[],False,16
    K,la=(N-B)//L+1,len(answer)
    for k in range(K+1):
        curr_incols=incols[L*k-la:L*(k+1)-la]
        curr_outcols=outcols[L*k:L*(k+1)]
        for i in range(len(curr_outcols)):
            if curr_outcols[i][-F:] not in curr_incols:
                answer.append(L*k+i)
                la=len(answer)
                if la==B:
                    booleban_answer=True
                    break
        if boolean_answer:
            break
    return answer 
T=int(input())
for i in range(T):
    N,B,F=map(int,input().split())
    outcols,incols=dat_bae_cols(N,B,F)
    if len(outcols[0])==len(incols[0]):
        answer=dat_bae_ans(N,B,F,outcols,incols)
    else:
        answer=dat_bae_fans(N,B,F,outcols,incols)
    print(' '.join(map(str,answer)),flush=True)
    ans=input()
    if ans!='1':  
        exit()

['01101010110101010101010101010010101010101010110101010010101010',
 '00100101101100110011001100110110011001101001101100110110011001',
 '00011100011100001111000011110001111000011000011100001110000111',
 '00000011111100000000111111110000000111111000000011111110000000',
 '00000000000011111111111111110000000000000111111111111110000000']

#14pts,20pts ✓ ✓
def dat_bae_cols(N,B,F):
    Nb=(N-1).bit_length()
    outcols=[format(i,'#0%db'%(Nb+2))[2:] for i in range(N)]
    incols=N*['']
    for j in range(Nb):
        if j>F-1:
            break
        outrow=''.join([outcols[i][Nb-j-1] for i in range(N)])
        print(outrow,flush=True)
        inrow=input()
        for i in range(N-B):
            incols[i]=inrow[i]+incols[i]
    return outcols,incols
def dat_bae_fans(N,B,F,outcols,incols):    
    answer,boolean_answer,L=[],False,16
    K,la=(N-B)//L+1,len(answer)
    for k in range(K+1):
        curr_incols=incols[L*k-la:L*(k+1)-la]
        curr_outcols=outcols[L*k:L*(k+1)]
        for i in range(len(curr_outcols)):
            if curr_outcols[i][-F:] not in curr_incols:
                answer.append(L*k+i)
                la=len(answer)
                if la==B:
                    booleban_answer=True
                    break
        if boolean_answer:
            break
    return answer 
T=int(input())
for i in range(T):
    N,B,F=map(int,input().split())
    outcols,incols=dat_bae_cols(N,B,F)
    answer=dat_bae_fans(N,B,F,outcols,incols)
    print(' '.join(map(str,answer)),flush=True)
    ans=input()
    if ans!='1':  
        exit()