# -*- coding: utf-8 -*-
"""codejamQ2020.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MAWt0zDQP8LH5Pr3YlDROXVWYMvmjDNQ

# Code Jam. Qualification Round 2020

# Task 1 Vestigium
$\displaystyle{\mathbb{\color{magenta}{Problem}}}$

Vestigium means "trace" in Latin. 

In this problem we work with Latin squares and matrix traces.

The trace of a square matrix is the sum of the values on the main diagonal 

(which runs from the upper left to the lower right).

An N-by-N square matrix is a Latin square if each cell contains one of N different values, 

and no value is repeated within a row or a column. 

In this problem, we will deal only with "natural Latin squares" in which 

the N values are the integers between 1 and N.

Given a matrix that contains only integers between 1 and N, 

we want to compute its trace and check whether it is a natural Latin square. 

To give some additional information, 

instead of simply telling us whether the matrix is a natural Latin square or not, 

please compute the number of rows and the number of columns that contain repeated values.

$Input$

The first line of the input gives the number of test cases, T. T test cases follow. 

Each starts with a line containing a single integer N: the size of the matrix to explore. 

Then, N lines follow. The i-th of these lines contains N integers $M_{i,1}$, $M_{i,2}$ ..., $M_{i,N}$. 

$M_{i,j}$ is the integer in the i-th row and j-th column of the matrix.

$Output$

For each test case, output one line containing `Case #x: k r c`, 

where x is the test case number (starting from 1), 

- k is the trace of the matrix, 
- r is the number of rows of the matrix that contain repeated elements, and 
- c is the number of columns of the matrix that contain repeated elements.

$Limits$

Test set 1 (Visible Verdict)

Time limit: 20 seconds per test set.

Memory limit: 1GB.

1 ≤ T ≤ 100.

2 ≤ N ≤ 100.

1 ≤ Mi,j ≤ N, for all i, j.

Sample

Input
 
3

4

1 2 3 4

2 1 4 3

3 4 1 2

4 3 2 1

4

2 2 2 2

2 3 2 3

2 2 2 3

2 2 2 2

3

2 1 3

1 3 2

1 2 3

Output

Case #1: 4 0 0

Case #2: 9 4 4

Case #3: 8 0 2

In `Sample Case #1`, the input is a natural Latin square, 

which means no row or column has repeated elements. 

All four values in the main diagonal are 1, and so the trace (their sum) is 4.

In `Sample Case #2`, all rows and columns have repeated elements. 

Notice that each row or column with repeated elements is counted only once 

regardless of the number of elements that are repeated or how often they are repeated within the row or column.

In addition, notice that some integers in the range 1 through N may be absent from the input.

In `Sample Case #3`, the leftmost and rightmost columns have repeated elements.
"""

T = int(input())
for t in range(T): 
    N = int(input())
    k, r, c = 0, 0, 0
    M = []
    for i in range(N):
        R = input()
        M.append([int(s) for s in R.split()])
        if len((set(M[i]))) < N: r += 1
        for j in range(N):
            if i == j: k += M[i][j]
            if i == N-1: 
                C = [M[i][j] for i in range(N)]
                if len((set(C))) < N: c += 1
    print('Case #%d: %d %d %d' % ((t+1, k, r, c)))

def check_list(arr):
    vis=set()
    out=0
    for x in arr:
        if x not in vis:
            vis.add(x)
        else: 
            out=1
            break 
    return out
T=int(input())
for t in range(T): 
    N=int(input())
    k,r,c=0,0,0
    M=[]
    for i in range(N):
        I=input().split()
        M.append([int(i) for i in I])
        r+=check_list(M[i])
        for j in range(N):
            if i==j:
                k+=M[i][j]
            if i==N-1: 
                c+=check_list([M[i][j] for i in range(N)])
    print('Case #%d: %d %d %d'%((t+1,k,r,c)))

"""# Task 2 Nesting Depth

$\displaystyle{\mathbb{\color{magenta}{Problem}}}$

Given a string of digits S, insert a minimum number of opening and closing parentheses into it 

such that the resulting string is balanced and each digit d is inside exactly d pairs of matching parentheses.

Let the nesting of two parentheses within a string be the substring that occurs strictly between them. 

An opening parenthesis and a closing parenthesis that is further to its right are said 

to match if their nesting is empty, or if every parenthesis in their nesting matches 

with another parenthesis in their nesting. 

The nesting depth of a position p is the number of pairs of matching parentheses m such that 

p is included in the nesting of m.

For example, in the following strings, all digits match their nesting depth: 

$0((2)1), (((3))1(2)), ((((4)))), ((2))((2))(1)$. 

The first three strings have minimum length among those that have the same digits in the same order, 

but the last one does not since $((22)1)$ also has the digits 221 and is shorter.

Given a string of digits S, find another string S', comprised of parentheses and digits, such that:

all parentheses in S' match some other parenthesis,
removing any and all parentheses from S' results in S,

each digit in S' is equal to its nesting depth, and
S' is of minimum length.

$Input$

The first line of the input gives the number of test cases, T. T lines follow. 

Each line represents a test case and contains only the string S.

$Output$

For each test case, output one line containing `Case #x: y`, 

where x is the test case number (starting from 1) and y is the string S' defined above.

$Limits$

Time limit: 20 seconds per test set.

Memory limit: 1GB.

1 ≤ T ≤ 100.

1 ≤ length of S ≤ 100.

Test set 1 (Visible Verdict)

Each character in S is either 0 or 1.

Test set 2 (Visible Verdict)

Each character in S is a decimal digit between 0 and 9, inclusive.

Sample

Input
 
4

0000

101

111000

1

Output
  
Case #1: 0000

Case #2: (1)0(1)

Case #3: (111)000

Case #4: (1)

  
The strings $()0000()$, $(1)0(((()))1)$ and $(1)(11)000$ are not valid solutions to 

`Sample Cases #1`, `#2` and `#3`, respectively, only because they are not of minimum length. 

In addition, 1)( and )(1 are not valid solutions to `Sample Case #4` because 

they contain unmatched parentheses and the nesting depth is 0 at the position where there is a 1.

You can create sample inputs that are valid only for Test Set 2 by removing the parentheses 

from the example strings mentioned in the problem statement.
"""

T = int(input())
for t in range(T): 
    S = str(input())
    N = [int(n) for n in S]
#    print(N)
    R = N[0] * '(' + str(N[0])
    for i in range(1,len(N)):
        if (N[i - 1] < N[i]):
            nopen = N[i] - N[i - 1]
 #           print('o'+str(nopen))
            R += nopen * '(' + str(N[i])
        elif N[i - 1] > N[i]:
            nclose = (N[i - 1] - N[i])
            R += nclose * ')' + str(N[i])
 #           print('c'+str(nclose))
        else:
            R += str(N[i])
    R += N[-1] * ')' 
    print('Case #%d: %s' % ((t + 1, R)))

def gen_str(s):
    s0=int(s[0])
    yield s0*'('+s[0]
    while s[:-1]:
        s=s[1:]
        s1=int(s[0])
        c=s1>s0
        yield c*(s1-s0)*'('+(not c)*(s0-s1)*')'+s[0]
        s0=s1
    yield s0*')'
T=int(input())
for t in range(T):
    S=input()
    print('Case #%d: %s'%((t+1,''.join(gen_str(S)))))

"""# Task 3 Parenting Partnering Returns

$\displaystyle{\mathbb{\color{magenta}{Problem}}}$

Cameron and Jamie's kid is almost 3 years old! 

However, even though the child is more independent now,

scheduling kid activities and domestic necessities is still a challenge for the couple.

Cameron and Jamie have a list of N activities to take care of during the day. 

Each activity happens during a specified interval during the day. 

They need to assign each activity to one of them, 

so that neither of them is responsible for two activities that overlap. 

An activity that ends at time t is not considered to overlap with another activity that starts at time t.

For example, suppose that Jamie and Cameron need to cover 3 activities: 
- one running from 18:00 to 20:00, 
- another from 19:00 to 21:00 and 
- another from 22:00 to 23:00. 

One possibility would be for Jamie to cover the activity running from 19:00 to 21:00, 

with Cameron covering the other two. 

Another valid schedule would be for Cameron to cover the activity from 18:00 to 20:00 and 

Jamie to cover the other two. 

Notice that the first two activities overlap in the time between 19:00 and 20:00, 

so it is impossible to assign both of those activities to the same partner.

Given the starting and ending times of each activity,

find any schedule that does not require the same person to cover overlapping activities, 

or say that it is impossible.

$Input$

The first line of the input gives the number of test cases, T. T test cases follow. 

Each test case starts with a line containing a single integer N, the number of activities to assign. 

Then, N more lines follow. 

The i-th of these lines (counting starting from 1) contains two integers Si and Ei. 

The i-th activity starts exactly Si minutes after midnight and ends exactly Ei minutes after midnight.

$Output$

For each test case, output one line containing `Case #x: y`, 

where x is the test case number (starting from 1) and 

y is IMPOSSIBLE if there is no valid schedule according to the above rules, 

or a string of exactly N characters otherwise. 

The i-th character in y must be 

C if the i-th activity is assigned to Cameron in your proposed schedule, 

and J if it is assigned to Jamie.

If there are multiple solutions, you may output any one of them. 

(See "What if a test case has multiple correct solutions?" in the Competing section of the FAQ. 

This information about multiple solutions will not be explicitly stated in the remainder of the 2020 contest.)

$Limits$

Time limit: 20 seconds per test set.

Memory limit: 1GB.

1 ≤ T ≤ 100.

0 ≤ Si < Ei ≤ 24 × 60.

Test set 1 (Visible Verdict)

2 ≤ N ≤ 10.

Test set 2 (Visible Verdict)

2 ≤ N ≤ 1000.

Sample

Input
 
4

3

360 480

420 540

600 660

3

0 1440

1 3

2 4

5

99 150

1 100

100 301

2 5

150 250

2

0 720

720 1440

Output
  
Case #1: CJC

Case #2: IMPOSSIBLE

Case #3: JCCJJ

Case #4: CC

  
`Sample Case #1` is the one described in the problem statement. 

As mentioned above, there are other valid solutions, like JCJ and JCC.

In `Sample Case #2`, all three activities overlap with each other. 

Assigning them all would mean someone would end up with at least two overlapping activities, 

so there is no valid schedule.

In `Sample Case #3`, notice that Cameron ends an activity and starts another one at minute 100.

In `Sample Case #4`, any schedule would be valid. Specifically, 

it is OK for one partner to do all activities.

"""

T=int(input())
for t in range(T): 
    N=int(input())
    I=[input() for i in range(N)]
    ANS=N*'O'
    A=sorted([list(map(int,I[i].split()))+[i] 
              for i in range(N)])
#    print(A)
    endC,endJ=0,0
    for a in A:
 #       print(a[0],a[1],a[2])
        if endC<=a[0]:
            ANS=ANS[:a[2]]+'C'+ANS[a[2]+1:]
            endC=a[1]
        elif endJ<=a[0]:
            ANS=ANS[:a[2]]+'J'+ANS[a[2]+1:]
            endJ=a[1]
        else:
            ANS='IMPOSSIBLE'
            break
    print('Case #{}: {}'.format(t+1,ANS))

#3
#360 480 #420 540 #600 660
#3
#0 1440 #1 3 #2 4
#5
#99 150 #1 100 #100 301 #2 5 #150 250
#2
#0 720 #720 1440

"""# Task 4

$\displaystyle{\mathbb{\color{magenta}{Problem}}}$

Last year, a research consortium had some trouble with a distributed database system 

that sometimes lost pieces of the data. 

You do not need to read or understand that problem in order to solve this one!

The consortium has decided that distributed systems are too complicated, 

so they are storing B bits of important information in a single array on one awesome machine. 

As an additional layer of security, they have made it difficult to obtain the information quickly; 

the user must query for a bit position between 1 and B, and 

then they receive that bit of the stored array as a response.

Unfortunately, this ultra-modern machine is subject to random quantum fluctuations! 

Specifically, after every 1st, 11th, 21st, 31st... etc. query is sent, 

but before the response is given, quantum fluctuation causes exactly one of the following four effects, 

with equal probability:
- 25% of the time, the array is complemented:
-- every 0 becomes a 1, and vice versa.
- 25% of the time, the array is reversed:
-- the first bit swaps with the last bit, 
-- the second bit swaps with the second-to-last bit, 
-- and so on.
- 25% of the time, both of the things above (complementation and reversal) happen to the array.
-- (Notice that the order in which they happen does not matter.)
- 25% of the time, nothing happens to the array.

Moreover, there is no indication of what effect the quantum fluctuation has had each time. 

The consortium is now concerned, and it has hired you to get its precious data back, in whatever form it is in!

Can you find the entire array, such that your answer is accurate as of the time that you give it? 

Answering does not count as a query, so if you answer after your 30th query, for example, 

the array will be the same as it was after your 21st through 30th queries.

$Input \; and \; output$

This is an interactive problem. 

You should make sure you have read the information in the Interactive Problems section of our FAQ.

Initially, your program should read a single line containing two integers T and B: 

the number of test cases and the number of bits in the array, respectively. 

Note that B is the same for every test case.

Then, you need to process T test cases. 

In each case, the judge begins with a predetermined B-bit array; 

note that this array can vary from test case to test case, and is not necessarily chosen at random. 

Then, you may make up to 150 queries of the following form:

Your program outputs one line containing a single integer P between 1 and B, inclusive, 

indicating which position in the array you wish to look at.

If the number of queries you have made so far ends with a 1, 

the judge chooses one of the four possibilities described above 

(complementation, reversal, complementation + reversal, or nothing), 

uniformly at random and independently of all other choices, and alters the stored array accordingly. 

(Notice that this will happen on the very first query you make.)

The judge responds with one line containing a single character 0 or 1, 

the value it currently has stored at bit position P, or N if you provided a malformed line 

(e.g., an invalid position).

Then, after you have made as many of the 150 queries above as you want, 

you must make one more exchange of the following form:

Your program outputs one line containing a string of B characters, 

each of which is 0 or 1, representing the bits currently stored in the array

(which will not necessarily match the bits that were initially present!)

The judge responds with one line containing a single letter: 

- uppercase Y if your answer was correct, and 
- uppercase N if it was not (or you provided a malformed line). 

If you receive Y, you should begin the next test case, 

or stop sending input if there are no more test cases.

After the judge sends N to your input stream, it will not send any other output. 

If your program continues to wait for the judge after receiving N, 

your program will time out, resulting in a Time Limit Exceeded error. 

Notice that it is your responsibility to have your program exit in time 

to receive a Wrong Answer judgment instead of a Time Limit Exceeded error. 

As usual, if the memory limit is exceeded, or your program gets a runtime error, 

you will receive the appropriate judgment.

$Limits$

Time limit: 40 seconds per test set.

Memory limit: 1GB.

1 ≤ T ≤ 100.

Test set 1 (Visible Verdict)

B = 10.

Test set 2 (Visible Verdict)

B = 20.

Test set 3 (Hidden Verdict)

B = 100.

#### <i>Testing Tool</i>

You can use this testing tool to test locally or on our servers. 

To test locally, you will need to run the tool in parallel with your code; 

you can use our interactive runner for that. 

The interactive runner was changed after the 2019 contest. 

Be sure to download the latest version. 

For more information, read the Interactive Problems section of the FAQ.


#### <i>Local Testing Tool</i>

To better facilitate local testing, we provide you the following script. 

Instructions are included inside. 

You are encouraged to add more test cases for better testing. 

Please be advised that although the testing tool is intended to simulate the judging system, 

it is NOT the real judging system and might behave differently.


If your code passes the testing tool but fails the real judge, 

please check the Coding section of our FAQ to make sure that you are using the same compiler as us.


#### <i>Sample Interaction</i>

The following interaction corresponds to Test Set 1.
<pre><code>
  t, b = readline_int_list()      
  
  // reads 100 into t and 10 into b.

  // The judge starts with the predetermined array for this test case:

  // 0001101111. (Note: the actual Test Set 1 will not necessarily

  // use this array.)
  
  printline 1 to stdout   
  
  // we ask about position 1.

  flush stdout

  // Since this is our 1st query, and 1 is 1 mod 10, the judge secretly and

  // randomly chooses one of the four possible quantum fluctuation effects, as

  // described above. It happens to choose complementation + reversal, so now

  // the stored value is 0000100111.

  r = readline_chr()      // reads 0.

  printline 6 to stdout   // we ask about position 6.

  flush stdout

  // Since this is our 2nd query, and 2 is 2 mod 10, the judge does not choose

  // a quantum fluctuation effect.

  r = readline_chr()      // reads 0.

  ...

  // We have omitted the third through tenth queries in this example.

  ...

  printline 1 to stdout   // we decide to ask about position 1 again.

  flush stdout

  // Since this is our 11th query, and 11 is 1 mod 10, the judge secretly and

  // randomly chooses a quantum fluctuation effect, and happens to get

  // reversal, so now the stored value is 1110010000.

  r = readline_chr()      // reads 1.

  printline 1110110000 to stdout   // we try to answer. why?!?!

  flush stdout

  ok = readline_chr()     // reads N -- we have made a mistake!

  exit                    // exits to avoid an ambiguous TLE error
</code></pre>
"""

# 1pts
def get10():
    inrow=''
    for i in range(10):
        outid=str(i+1)
        print(outid,flush=True)
        inrow+=input()
    return inrow
T,B=map(int,input().split())
for t in range(T):
    inrow=get10()
    print(inrow,flush=True)
    answer=input()
    if answer!='Y':  
        exit()

def get2(inrow,i,n,complement,reverse):
    print(str(i+1),flush=True)
    answer1=input()
    print(str(n-i-1),flush=True)
    answer2=input()
    if (complement==None and answer1==answer2):
        complement=i
    if (reverse==None and answer1!=answer2):
        reverse=i
    inrow=inrow[:i]+answer1+inrow[i+1:n-i-1]+answer2+inrow[n-i:]
    return inrow,complement,reverse
n,complement,reverse=20,None,None
inrow=n*'?'
for i in range(2):
    inrow,complement,reverse=get2(inrow,i,n,complement,reverse)
    print(inrow,complement,reverse,'?' in inrow)

def complemented(string):
    return string.replace('0','*')\
    .replace('1','0').replace('*','1')
reversed(inrow),complemented(inrow)

x=int('1011101011',2)
y=~x&1023
print(x,y,'=>',format(x,'010b'),format(y,'010b'))
print(1023-y,1023-x)

# complementation
x=int('1011101011',2)
y=1023-x
print(x,y,'=>',format(x,'010b'),format(y,'010b'))

# reverse
bx='1011101011'
by=bx[::-1]
print(bx,by,'=>',int(bx,2),int(by,2))

# reverse & complementation
bx='1011101011'
by=format(1023-int(bx[::-1],2),'010b')
print(bx,by,'=>',int(bx,2),int(by,2))

def fluctuation(x):
    n=len(x)
    return [x,format(2**n-1-int(x,2),'0%db'%n),
            x[::-1],format(2**n-1-int(x[::-1],2),'0%db'%n)]
fluctuation('1011101011')

def query(string):
    print(string,flush=True)
    return input()    
def update_by_pairs(i,b,inrow,complement,reverse):
    answer1=query(str(i+1))
    answer2=query(str(b-i))
    if (complement==None and answer1==answer2):
        complement=i
    if (reverse==None and answer1!=answer2):
        reverse=i
    inrow=inrow[:i]+answer1+inrow[i+1:b-i-1]+answer2+inrow[b-i:]
    return inrow,complement,reverse
def is_complemented(string,complement):
    if (complement==None):
        query('1')
    else:
        if string[complement]!=query(str(complement+1)):
            string=string.replace('0','*')\
            .replace('1','0').replace('*','1')
    return string
def is_reversed(string,reverse):
    if (reverse==None):
        query('1')
    else:
        if string[reverse]!=query(str(reverse+1)):
            string=string[::-1]
    return string
t,b=map(int,input().split())
for case in range(t):
    inrow,start,complement,reverse=b*'?',5,None,None
    for i in range(start):
        inrow,complement,reverse=\
        update_by_pairs(i,b,inrow,complement,reverse)
    while ('?' in inrow and start<b//2):
        if start%4==1:
            inrow=is_complemented(inrow,complement)
            inrow=is_reversed(inrow,reverse)
        inrow,complement,reverse=\
        update_by_pairs(start,b,inrow,complement,reverse)
        start+=1
    answer=query(inrow)
    if answer!='Y':  
        exit()

class QuantumString:
    def __init__(self,length):
        self.B=length
        self.R=length*'?'
        self.Q=''
        self.count=0
        self.start=5
        self.complement=None
        self.reverse=None
    def query(self):
        print(self.Q,flush=True)
        self.count+=1
        return input()    
    def update_by_pairs(self,i):
        self.Q=str(i+1); b1=self.query()
        self.Q=str(self.B-i); b2=self.query()
        if (self.complement==None and b1==b2):
            self.complement=i
        if (self.reverse==None and b1!=b2):
            self.reverse=i
        self.R=self.R[:i]+b1+self.R[i+1:self.B-i-1]+\
               b2+self.R[self.B-i:]
    def is_complemented(self):
        if (self.complement==None):
            self.Q='1'; self.query()
        else:
            self.Q=str(self.complement+1)
            if self.R[self.complement]!=self.query():
                self.R=self.R.replace('0','*')\
                           .replace('1','0').replace('*','1')
    def is_reversed(self):
        if (self.reverse==None):
            self.Q='1'; self.query()
        else:
            self.Q=str(self.reverse+1)
            if self.R[self.reverse]!=self.query():
                self.R=self.R[::-1]
    def find_string(self):
        for i in range(self.start):
            self.update_by_pairs(i)
        while ('?' in self.R and self.start<self.B//2):
            if self.start%4==1:
                self.is_complemented()
                self.is_reversed()
            self.update_by_pairs(self.start)
            self.start+=1
        print(self.R,flush=True)
        if input()!='Y':
            exit()
t,b=map(int,input().split())
for case in range(t):
    QS=QuantumString(b)
    QS.find_string()

"""# Task 5

$\displaystyle{\mathbb{\color{magenta}{Problem}}}$

Indicium means "trace" in Latin. In this problem we work with Latin squares and matrix traces.

A Latin square is an N-by-N square matrix in which each cell contains one of N different values, 

such that no value is repeated within a row or a column. 

In this problem, we will deal only with "natural Latin squares" in 

which the N values are the integers between 1 and N.

The trace of a square matrix is the sum of the values on the main diagonal 

(which runs from the upper left to the lower right).

Given values N and K, produce any N-by-N "natural Latin square" with trace K, or say it is impossible. 

For example, here are two possible answers for N = 3, K = 6. In each case, 

the values that contribute to the trace are underlined.

`2 1 3` ___  `3 1 2`

`3 2 1` ___  `1 2 3`

`1 3 2` ___  `2 3 1`

$Input$

The first line of the input gives the number of test cases, T. T test cases follow. 

Each consists of one line containing two integers N and K: the desired size of the matrix and the desired trace.

$Output$

For each test case, output one line containing 

`Case #x: y`, 

where x is the test case number (starting from 1) and y is 
- IMPOSSIBLE if there is no answer for the given parameters or 
- POSSIBLE otherwise. 

In the latter case, output N more lines of 

N integers each, representing a valid "natural Latin square" 

with a trace of K, as described above.

$Limits$

Time limit: 20 seconds per test set.

Memory limit: 1GB.

N ≤ K ≤ N^2.

Test set 1 (Visible Verdict)

T = 44.

2 ≤ N ≤ 5.

Test set 2 (Hidden Verdict)

1 ≤ T ≤ 100.

2 ≤ N ≤ 50.
"""

M=[[3,1,2,4,5,6],[4,3,1,5,6,2],
   [5,4,3,6,2,1],[6,5,4,2,1,3],
   [2,6,5,1,3,4],[1,2,6,3,4,5]]
def display_matrix(M):
    MS=''
    for i in range(len(M)):
        MS+=' '.join([str(r) for r in M[i]])+'\n'
    print(MS)
def trace(arr):
    arr_trace,i=0,0
    for row in arr:
        arr_trace+=row[i]
        i+=1
    return arr_trace
MT=trace(M)
display_matrix(M)
M,MT

def gen_permutations(arr):
    if len(arr)<=1: yield arr
    else:
        for p in gen_permutations(arr[1:]):
            for i in range(len(arr)):
                yield p[:i]+arr[0:1]+p[i:]
def find_matrix(N,S):
    row=list(range(1,N+1))
    row_gen=gen_permutations(row)
    flag,result=False,[]
    for row in row_gen:
        matrix=[[row[j%len(row)] 
                 for j in range(i,i+len(row))] 
                for i in range(len(row))]
        matrix_gen=gen_permutations(matrix)
        for rows in matrix_gen:
            if trace(rows)==S:
                flag=True
                result=rows
                break
        if flag:
            break
    return result
N=5
for s in range(N+3,N*N-2):
    display_matrix(find_matrix(N,s))
    print(s)

def find_matrix2(N,S):
    if S==N+2:
        base=list(range(1,N+1))
    elif S==N*N-2:
        base=list(range(N,0,-1))
    elif S==(N-2)*3+4:
        base=[3,2,1,4]+list(range(5,N+1))
    matrix=[base]
    for i in range(1,N):
        if i%2==1:
            base,row=matrix[i-1],[]
            for j in range(N//2):
                row+=[base[2*j+1],base[2*j]]
            matrix.append(row)
        else:
            matrix.append(base[-2:]+base[:-2])
    return matrix[:N-2]+[matrix[N-1],matrix[N-2]]
def find_matrix1(N,S):
    matrix=[]
    cols={i:list(range(1,N+1)) for i in range(N)}
    if S==N*N-2:
        base=[N,N-1]+list(range(1,N-1))
        r1=[N-1]+list(range(2,N-2))+[N,N-2,1]
        r2=[k+2 if k%2==0 else k for k in range(N-3)]+[N-2,N-1,N]
    elif S==N+2:
        base=list(range(1,N+1))
        r1=[2,4]+list(range(5,N))+[1,N,3]
        r2=[4,3]+[k+2 if k%2==0 else k for k in range(4,N-1)]+[N,2,1]
    elif S==(N-2)*3+4:
        base=[3,2,1,4]+list(range(5,N+1))
        r1=[2,4]+list(range(5,N))+[3,N,1]
        r2=[4,1]+[k+2 if k%2==0 else k for k in range(4,N-1)]+[N,2,3]
    for i in range(N-3):
        row=base[N-i:]+base[:N-i]
        matrix.append(row)
    matrix.append(r1)
    matrix.append(r2)
    for row in matrix:
        for k in range(N):
            cols[k].remove(row[k])
    matrix.append([cols[k][0] for k in range(N)])
    return matrix
M2=find_matrix2(10,(10-2)*3+4)
print(trace(M2),'\n')
display_matrix(M2)
M1=find_matrix1(11,(11-2)*3+4)
print(trace(M1),'\n')
display_matrix(M1)
M2,M1

def check_list(lst):
    vis=set()
    out=0
    for x in lst:
        if x not in vis:
            vis.add(x)
        else: 
            out=1
            break 
    return out
def check_matrix(matrix):
    N,C=len(matrix),0
    cols={i:[] for i in range(N)}
    for i in range(N):
        row=matrix[i]
        C+=check_list(row)
        for j in range(N):
            cols[j]+=[row[j]]
    for j in range(N):
        C+=check_list(cols[j])
    return C
check_matrix(M3)

def gen_xyz(N,K):
    min_x=max(1,(K-2*N)//(N-2))
    max_x=min(N,(K-2)//(N-2))
    for x in range(min_x,max_x+1):
        for y in range(1,N+1):
            for z in range(1,N+1):
                if (N-2)*x+y+z==K and (x==y) is (x==z):
                        return [x,y,z]
def find_matrix(N,K):
    X,Y,Z=gen_xyz(N,K)
    M=[i*[0]+[X]+(N-i-1)*[0] for i in range(N-2)]
    M+=[(N-2)*[0]+[Y,X]]
    M+=[(N-2)*[0]+[X,Z]]
    col_set={i:{X} for i in range(N-2)}
    col_set[N-2]={X,Y}; col_set[N-1]={X,Z}
    base=[X,Y,Z]
    base+=list(set(range(1,N+1))-set(base))
    for b in base:
        for r in range(N):
            if b not in M[r]:
                for c in [i%N for i in range(r,r+N)]:
                    if M[r][c]==0 and b not in col_set[c]:
                        M[r]=M[r][:c]+[b]+M[r][c+1:]
                        col_set[c].add(b)
                        break
    return M
N,S=8,37
[X,Y,Z]=gen_xyz(N,S)
M3=find_matrix(N,S)
M3,trace(M3)

def display_matrix(M):
    MS=''
    for i in range(len(M)):
        MS+=' '.join([str(r) for r in M[i]])+'\n'
    print(MS)
def trace(arr):
    arr_trace,i=0,0
    for row in arr:
        arr_trace+=row[i]
        i+=1
    return arr_trace
def gen_permutations(arr):
    if len(arr)<=1: yield arr
    else:
        for p in gen_permutations(arr[1:]):
            for i in range(len(arr)):
                yield p[:i]+arr[0:1]+p[i:]     
def find_matrix0(N,S):
    baseN=S//N
    baseR=list(range(1,N+1))
    baseR=baseR[baseN-1:]+baseR[:baseN-1]
    return [baseR[i:]+baseR[:i] for i in range(N,0,-1)]
def find_matrix_gen(N,S):
    row=list(range(1,N+1))
    row_gen=gen_permutations(row)
    flag,result=False,[]
    for row in row_gen:
        matrix=[[row[j%len(row)] 
                 for j in range(i,i+len(row))] 
                for i in range(len(row))]
        matrix_gen=gen_permutations(matrix)
        for rows in matrix_gen:
            if trace(rows)==S:
                flag=True
                result=rows
                break
        if flag:
            break
    return result
def find_matrix1(N,S):
    matrix=[]
    cols={i:list(range(1,N+1)) for i in range(N)}
    if S==N*N-2:
        base=[N,N-1]+list(range(1,N-1))
        r1=[N-1]+list(range(2,N-2))+[N,N-2,1]
        r2=[k+2 if k%2==0 else k for k in range(N-3)]+[N-2,N-1,N]
    elif S==N+2:
        base=list(range(1,N+1))
        r1=[2,4]+list(range(5,N))+[1,N,3]
        r2=[4,3]+[k+2 if k%2==0 else k for k in range(4,N-1)]+[N,2,1]
    elif S==(N-2)*3+4:
        base=[3,2,1,4]+list(range(5,N+1))
        r1=[2,4]+list(range(5,N))+[3,N,1]
        r2=[4,1]+[k+2 if k%2==0 else k for k in range(4,N-1)]+[N,2,3]
    for i in range(N-3):
        row=base[N-i:]+base[:N-i]
        matrix.append(row)
    matrix.append(r1)
    matrix.append(r2)
    for row in matrix:
        for k in range(N):
            cols[k].remove(row[k])
    matrix.append([cols[k][0] for k in range(N)])
    return matrix
def find_matrix2(N,S):
    if S==N+2:
        base=list(range(1,N+1))
    elif S==N*N-2:
        base=list(range(N,0,-1))
    elif S==(N-2)*3+4:
        base=[3,2,1,4]+list(range(5,N+1))
    matrix=[base]
    for i in range(1,N):
        if i%2==1:
            base,row=matrix[i-1],[]
            for j in range(N//2):
                row+=[base[2*j+1],base[2*j]]
            matrix.append(row)
        else:
            matrix.append(base[-2:]+base[:-2])
    return matrix[:N-2]+[matrix[N-1],matrix[N-2]]  
T=int(input())
for t in range(T): 
    N,K=map(int,input().split())
    cond2=(N==2) and (K==3)
    cond3=(N==3) and (K in [4,5,7,8])
    cond4=(N>3) and (K in [N+1,N*N-1])
    cond=cond2 or cond3 or cond4
    if cond:
        print('Case #{}: IMPOSSIBLE'.format(t+1))
    else:
        if K%N==0:
            M=find_matrix0(N,K)
        elif K not in [N+2,N*N-2,(N-2)*3+4]:
            M=find_matrix_gen(N,K)
        else:
            if K%2==1:
                M=find_matrix1(N,K)
            else:
                M=find_matrix2(N,K)
        print('Case #{}: POSSIBLE'.format(t+1))
        display_matrix(M)

def display_matrix(M):
    MS=''
    for i in range(len(M)):
        MS+=' '.join([str(r) for r in M[i]])+'\n'
    print(MS)
def find_matrix0(N,S):
    baseN=S//N
    baseR=list(range(1,N+1))
    baseR=baseR[baseN-1:]+baseR[:baseN-1]
    return [baseR[i:]+baseR[:i] for i in range(N,0,-1)]
def gen_xyz(N,K):
    min_x=max(1,(K-2*N)//(N-2))
    max_x=min(N,(K-2)//(N-2))
    for x in range(min_x,max_x+1):
        for y in range(1,N+1):
            for z in range(1,N+1):
                if (N-2)*x+y+z==K and (x==y) is (x==z):
                        return [x,y,z]
def find_matrix(N,K):
    X,Y,Z=gen_xyz(N,K)
    M=[i*[0]+[X]+(N-i-1)*[0] for i in range(N-2)]
    M+=[(N-2)*[0]+[Y,X]]
    M+=[(N-2)*[0]+[X,Z]]
    col_set={i:{X} for i in range(N-2)}
    col_set[N-2]={X,Y}; col_set[N-1]={X,Z}
    base=[X,Y,Z]
    base+=list(set(range(1,N+1))-set(base))
    for b in base:
        for r in range(N):
            if b not in M[r]:
                for c in [i%N for i in range(r,r+N)]:
                    if M[r][c]==0 and b not in col_set[c]:
                        M[r]=M[r][:c]+[b]+M[r][c+1:]
                        col_set[c].add(b)
                        break
    return M
T=int(input())
for t in range(T): 
    N,K=map(int,input().split())
    cond2=(N==2) and (K==3)
    cond3=(N==3) and (K in [4,5,7,8])
    cond4=(N>3) and (K in [N+1,N*N-1])
    cond=cond2 or cond3 or cond4
    if cond:
        print('Case #{}: IMPOSSIBLE'.format(t+1))
    else:
        if K%N==0:
            M=find_matrix0(N,K)
        else:
            M=find_matrix(N,K)
        print('Case #{}: POSSIBLE'.format(t+1))
        display_matrix(M)

class MGraph:
    def __init__(self,case,num,diag_sum):
        self.T=case+1
        self.N=num
        self.S=diag_sum
        self.M={i:num*[0] for i in range(num)}
        self.D=num*[0]
        self.XYZ=3*[0]
        cond1=(num==2) and (diag_sum==3)
        cond2=(num==3) and (diag_sum in [4,5,7,8])
        cond3=(num>3) and (diag_sum in [num+1,num**2-1])
        self.C=cond1 or cond2 or cond3
    def find_diagonal(self):
        if not self.C:
            if not self.S%self.N:
                self.D=self.N*[self.S//self.N]
            else:
                min_x=max(1,(self.S-2*self.N)//(self.N-2))
                max_x=min(self.N,(self.S-2)//(self.N-2))
                for x in range(min_x,max_x+1):
                    for y in range(1,self.N+1):
                        for z in range(1,self.N+1):
                            if (self.N-2)*x+y+z==self.S \
                            and (x==y) is (x==z):
                                self.D=(self.N-2)*[x]+[y,z]
                                self.XYZ=[x,y,z]
    def latin_square(self,prefix='Case #%d: '):
        if self.C: 
            print(prefix%self.T+'IMPOSSIBLE')
        else:
            if not self.S%self.N:
                base=list(range(1,self.N+1))
                base=base[self.S//self.N-1:]+base[:self.S//self.N-1]
                for i in range(self.N):
                    self.M[i]=base[self.N-i:]+base[:self.N-i]
            else:
                for i in range(self.N-2):
                    self.M[i]=i*[0]+[self.XYZ[0]]+(self.N-i-1)*[0]
                self.M[self.N-2]=(self.N-2)*[0]+[self.XYZ[1],self.XYZ[0]]
                self.M[self.N-1]=(self.N-2)*[0]+[self.XYZ[0],self.XYZ[2]]
                col_set={i:{self.XYZ[0]} for i in range(self.N-2)}
                col_set[self.N-2]={self.XYZ[0],self.XYZ[1]}
                col_set[self.N-1]={self.XYZ[0],self.XYZ[2]}
                base=self.XYZ
                base+=list(set(range(1,self.N+1))-set(base))
                for b in base:
                    for r in range(self.N):
                        if b not in self.M[r]:
                            for c in [i%self.N for i in range(r,r+self.N)]:
                                if self.M[r][c]==0 and b not in col_set[c]:
                                    self.M[r]=self.M[r][:c]+[b]+self.M[r][c+1:]
                                    col_set[c].add(b)
                                    break
            print(prefix%self.T+'POSSIBLE')
            str_matrix=''
            for i in range(self.N):
                str_row=[str(m) for m in self.M[i]]
                str_matrix+=' '.join(str_row)
            print(str_matrix)
T=int(input())
for case in range(T): 
    num,diag_sum=map(int,input().split())
    mg=MGraph(case,num,diag_sum)
    mg.find_diagonal()
    mg.latin_square()

"""
2
3 6
2 3

Case #1: POSSIBLE

2 1 3
3 2 1
1 3 2

Case #2: IMPOSSIBLE
"""